#include<stdio.h>
#include<conio.h>
void main()
{
clrscr();
int arr[5],i,*ptr;

printf("Eneter a arry element");
for(i=0;i<=4;i++)
	     {
	       scanf("%d\n",&arr[i]);
	      // int count=i;
	       //if(count==5)
	       //{
	       //printf("%d",arr[i]);
	       //}
	     }


      printf("u enterd the element");
      for(i=0;i<=4;i++)
      {
      printf("%d\n",arr[i]);
      }

//   printf("the 7 value=%d",*ptr);

     getch();

}